"use client";

import { useEffect, useState } from "react";
import { api } from "@/lib/api";
import type { BriefEvidence, LongitudinalRecordContext, PersistedInsightSnapshot } from "@/lib/types";

type Props = {
  onViewEvidence: (evidence: BriefEvidence) => void;
  recordContext?: LongitudinalRecordContext;
};

function savedContentText(content: Record<string, unknown>) {
  for (const field of ["text", "summary", "narrative", "title"]) {
    const value = content[field];
    if (typeof value === "string" && value.trim()) return value;
  }
  return "This saved item needs clinician review.";
}

function evidenceSources(item: PersistedInsightSnapshot["items"][number]): BriefEvidence[] {
  return item.evidence.flatMap((source) => source.transcript_segment_id && source.session_id ? [{
    evidence_id: source.transcript_segment_id,
    session_id: `session-${source.session_id}`,
    session_label: source.session_label ?? "Completed session",
    segment_index: source.segment_index,
    start: source.start,
    end: source.end,
    quote: source.quote,
  }] : []);
}

function EvidenceLinks({ evidence, onViewEvidence }: { evidence: BriefEvidence[]; onViewEvidence: Props["onViewEvidence"] }) {
  return <div className="mt-3 flex flex-wrap gap-x-3 gap-y-1.5">
    {evidence.map((source) => <button key={source.evidence_id} type="button" onClick={() => onViewEvidence(source)} className="cursor-grab text-xs font-medium text-emerald-800 underline decoration-stone-400 underline-offset-3 transition duration-200 ease-out hover:text-emerald-950 hover:decoration-emerald-700 active:cursor-grabbing focus-visible:rounded-sm focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-emerald-700">{source.session_label.replace("Synthetic · Elena Sadić · ", "")}</button>)}
  </div>;
}

function PersistedClientInsights({ snapshot, onViewEvidence }: { snapshot: PersistedInsightSnapshot; onViewEvidence: Props["onViewEvidence"] }) {
  const visibleItems = snapshot.items.filter((item) => item.review_state !== "hidden");
  return <section className="text-left" aria-label="Saved clinical insights workspace">
    <header className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm">
      <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-medium text-emerald-800">Client insights</p><h2 className="mt-1 text-xl font-semibold tracking-tight text-stone-900">Longitudinal review</h2></div><span className="rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-medium text-emerald-900">{snapshot.status} · v{snapshot.version}</span></div>
      <p className="mt-5 max-w-3xl border-l-2 border-emerald-300 pl-4 text-[15px] leading-7 text-stone-700">{savedContentText(snapshot.content)}</p>
      <p className="mt-4 text-xs leading-5 text-stone-500">Generated by {snapshot.generator_name}; selection policy {snapshot.selection_policy_version}. Every displayed item remains linked to its source transcript.</p>
    </header>
    <section className="mt-6" aria-labelledby="saved-insights-heading">
      <div className="mb-3 flex items-baseline justify-between gap-3"><h2 id="saved-insights-heading" className="text-base font-semibold text-stone-900">Saved review items</h2><span className="text-xs text-stone-500">{visibleItems.length} visible of {snapshot.items.length}</span></div>
      <div className="grid gap-3">{visibleItems.map((item) => {
        const sources = evidenceSources(item);
        return <article key={item.id} className="rounded-xl border border-stone-200 bg-stone-50 p-4"><div className="flex flex-wrap items-start justify-between gap-2"><h3 className="text-sm font-semibold capitalize text-stone-900">{item.kind.replace("_", " ")}</h3><span className="rounded-full bg-stone-100 px-2 py-1 text-[11px] font-medium text-stone-700">{item.review_state}</span></div><p className="mt-3 text-sm leading-6 text-stone-700">{savedContentText(item.content)}</p>{sources.length ? <EvidenceLinks evidence={sources} onViewEvidence={onViewEvidence} /> : <p className="mt-3 text-xs text-stone-500">No transcript source is attached.</p>}</article>;
      })}</div>
    </section>
  </section>;
}

export function ClientInsights({ onViewEvidence, recordContext }: Props) {
  const [snapshot, setSnapshot] = useState<PersistedInsightSnapshot | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!recordContext) return;
    let cancelled = false;
    void api.getLatestInsightSnapshot(recordContext.organizationId, recordContext.clientId)
      .then((result) => { if (!cancelled) setSnapshot(result); })
      .catch((reason: unknown) => { if (!cancelled) setError(reason instanceof Error ? reason.message : "Could not load the clinical insights workspace."); });
    return () => { cancelled = true; };
  }, [recordContext]);

  if (!recordContext) return <section className="rounded-2xl border border-stone-200 bg-white p-5 text-left shadow-sm"><h2 className="text-lg font-semibold text-stone-900">Clinical insights</h2><p className="mt-3 text-sm text-stone-600">Open Insights from an authorized client workspace.</p></section>;
  if (error) return <section className="rounded-2xl border border-stone-200 bg-white p-5 text-left shadow-sm"><h2 className="text-lg font-semibold text-stone-900">Clinical insights</h2><p className="mt-3 text-sm text-red-700">{error}</p></section>;
  if (!snapshot) return <section className="rounded-2xl border border-stone-200 bg-white p-5 text-left shadow-sm"><h2 className="text-lg font-semibold text-stone-900">Clinical insights</h2><p className="mt-3 text-sm text-stone-600">Preparing the longitudinal record…</p></section>;
  return <PersistedClientInsights snapshot={snapshot} onViewEvidence={onViewEvidence} />;
}
