"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { RecordingControls } from "@/components/session-review/recording-controls";
import { TranscriptLibrary } from "@/components/session-review/transcript-library";
import { TranscriptViewer } from "@/components/session-review/transcript-viewer";
import { api } from "@/lib/api";
import type { Transcript, TranscriptListItem } from "@/lib/types";

const pause = (milliseconds: number) => new Promise((resolve) => window.setTimeout(resolve, milliseconds));

export function SessionWorkspace() {
  const [transcripts, setTranscripts] = useState<TranscriptListItem[]>([]); const [transcript, setTranscript] = useState<Transcript | null>(null); const [activeId, setActiveId] = useState<string | null>(null); const [activeSegment, setActiveSegment] = useState(-1); const [isPlaying, setIsPlaying] = useState(false); const [isRecording, setIsRecording] = useState(false); const [isBusy, setIsBusy] = useState(false); const [isSavingSpeakers, setIsSavingSpeakers] = useState(false); const [status, setStatus] = useState("Press record to begin."); const [libraryError, setLibraryError] = useState<string | null>(null);
  const recorder = useRef<MediaRecorder | null>(null); const stream = useRef<MediaStream | null>(null); const chunks = useRef<Blob[]>([]); const audio = useRef<HTMLAudioElement | null>(null);
  const loadLibrary = useCallback(async () => { try { setLibraryError(null); setTranscripts(await api.listTranscripts()); } catch (error) { setLibraryError(error instanceof Error ? error.message : "Could not load saved transcripts."); } }, []);
  useEffect(() => { void loadLibrary(); }, [loadLibrary]); useEffect(() => () => stream.current?.getTracks().forEach((track) => track.stop()), []);
  const openTranscript = async (id: string, message = "Viewing saved transcript.") => { try { const data = await api.getTranscript(id); setTranscript(data); setActiveId(id); setActiveSegment(-1); setStatus(message); } catch (error) { setStatus(error instanceof Error ? error.message : "Could not open transcript."); } };
  const waitForCompletion = async (id: string) => { while (true) { await pause(5000); const job = await api.getJobStatus(id); if (job.status === "COMPLETED") return; if (job.status === "FAILED") throw new Error(job.detail || "HealthScribe could not complete the recording."); setStatus(`HealthScribe status: ${job.status}…`); } };
  const sendRecording = async () => { stream.current?.getTracks().forEach((track) => track.stop()); setIsRecording(false); setIsBusy(true); setStatus("Transcribing…"); try { const blob = new Blob(chunks.current, { type: recorder.current?.mimeType || "audio/webm" }); const job = await api.uploadRecording(blob); setStatus("HealthScribe is processing the recording…"); await waitForCompletion(job.id); await openTranscript(job.id, "Done."); await loadLibrary(); } catch (error) { setStatus(error instanceof Error ? `Could not transcribe: ${error.message}` : "Could not transcribe the recording."); } finally { setIsBusy(false); } };
  const toggleRecording = async () => { if (recorder.current?.state === "recording") { recorder.current.stop(); return; } try { stream.current = await navigator.mediaDevices.getUserMedia({ audio: true }); chunks.current = []; const nextRecorder = new MediaRecorder(stream.current); recorder.current = nextRecorder; nextRecorder.addEventListener("dataavailable", (event) => chunks.current.push(event.data)); nextRecorder.addEventListener("stop", () => void sendRecording(), { once: true }); nextRecorder.start(); setIsRecording(true); setStatus("Recording… press Stop when finished."); } catch (error) { setStatus(error instanceof Error ? `Microphone unavailable: ${error.message}` : "Microphone unavailable."); } };
  const playSegment = (index: number) => { const player = audio.current; if (!player || !transcript?.recording_url) { setStatus("Audio is not available for this transcript."); return; } if (index === activeSegment) { if (player.paused) void player.play().catch(() => setStatus("Audio playback could not start.")); else player.pause(); return; } player.currentTime = transcript.segments[index].start; setActiveSegment(index); void player.play().catch(() => setStatus("Audio playback could not start.")); };
  const onSpeakerChange = (speaker: string, value: string) => setTranscript((current) => current ? { ...current, speakers: { ...current.speakers, [speaker]: value.trim() || speaker } } : current);
  const saveSpeakers = async () => { if (!transcript || !activeId || activeId === "synthetic") return; setIsSavingSpeakers(true); try { const result = await api.saveSpeakerLabels(activeId, transcript.speakers); setTranscript({ ...transcript, speakers: result.speakers }); setStatus("Speaker names saved."); } catch (error) { setStatus(error instanceof Error ? error.message : "Could not save speaker names."); } finally { setIsSavingSpeakers(false); } };
  return <main className="mx-auto w-[min(94vw,1100px)] py-8 text-center"><RecordingControls isRecording={isRecording} isBusy={isBusy} onToggle={() => void toggleRecording()} /><p className="mt-5 min-h-6 text-sm text-stone-600" aria-live="polite">{status}</p><div className="mt-7 grid items-start gap-6 text-left md:grid-cols-[280px_1fr]"><TranscriptLibrary transcripts={transcripts} activeId={activeId} error={libraryError} onOpen={(id) => void openTranscript(id)} /><div ref={(node) => { audio.current = node?.querySelector("audio") ?? null; }}><TranscriptViewer transcript={transcript} activeSegment={activeSegment} isPlaying={isPlaying} onPlaySegment={playSegment} onAudioTimeUpdate={(event) => setActiveSegment(transcript?.segments.findIndex((segment) => event.currentTarget.currentTime >= segment.start && event.currentTarget.currentTime < segment.end) ?? -1)} onAudioPlay={() => setIsPlaying(true)} onAudioPause={() => setIsPlaying(false)} onAudioEnded={() => { setIsPlaying(false); setActiveSegment(-1); }} onSpeakerChange={onSpeakerChange} onSaveSpeakers={() => void saveSpeakers()} isSavingSpeakers={isSavingSpeakers} /></div></div></main>;
}
