"use client";

import { useCallback, useEffect, useRef, useState, useSyncExternalStore } from "react";
import { TranscriptLibrary } from "@/components/session-review/transcript-library";
import { SessionCardCarousel } from "@/components/session-review/session-card-carousel";
import { TranscriptViewer } from "@/components/session-review/transcript-viewer";
import { ScheduledSessionLayout } from "@/components/session-review/scheduled-session-layout";
import { CompletedSessionLayout } from "@/components/session-review/completed-session-layout";
import { ClientCareSettings } from "@/components/client-care-settings";
import { api } from "@/lib/api";
import type { Transcript, TranscriptListItem } from "@/lib/types";
import { readSessionView, subscribeToSessionView } from "@/lib/workspace-preferences";

const pause = (milliseconds: number) => new Promise((resolve) => window.setTimeout(resolve, milliseconds));

export function SessionWorkspace() {
  const [transcripts, setTranscripts] = useState<TranscriptListItem[]>([]); const [transcript, setTranscript] = useState<Transcript | null>(null); const [activeId, setActiveId] = useState<string | null>(null); const [activeSessionType, setActiveSessionType] = useState<"scheduled" | "completed">("scheduled"); const [activeSegment, setActiveSegment] = useState(-1); const [isPlaying, setIsPlaying] = useState(false); const [isRecording, setIsRecording] = useState(false); const [isBusy, setIsBusy] = useState(false); const [, setStatus] = useState("Press record to begin."); const [libraryError, setLibraryError] = useState<string | null>(null); const [isCareSettingsOpen, setIsCareSettingsOpen] = useState(false);
  const recorder = useRef<MediaRecorder | null>(null); const stream = useRef<MediaStream | null>(null); const chunks = useRef<Blob[]>([]); const audio = useRef<HTMLAudioElement | null>(null);
  const sessionView = useSyncExternalStore(subscribeToSessionView, readSessionView, () => "cards");
  const loadLibrary = useCallback(async () => { try { setLibraryError(null); setTranscripts(await api.listTranscripts()); } catch (error) { setLibraryError(error instanceof Error ? error.message : "Could not load saved transcripts."); } }, []);
  useEffect(() => { void loadLibrary(); }, [loadLibrary]); useEffect(() => () => stream.current?.getTracks().forEach((track) => track.stop()), []);
  const openTranscript = async (id: string, message = "Viewing saved transcript.") => { try { const data = await api.getTranscript(id); setTranscript(data); setActiveId(id); setActiveSessionType("completed"); setActiveSegment(-1); setStatus(message); } catch (error) { setStatus(error instanceof Error ? error.message : "Could not open transcript."); } };
  const waitForCompletion = async (id: string) => { while (true) { await pause(5000); const job = await api.getJobStatus(id); if (job.status === "COMPLETED") return; if (job.status === "FAILED") throw new Error(job.detail || "HealthScribe could not complete the recording."); setStatus(`HealthScribe status: ${job.status}…`); } };
  const sendRecording = async () => { stream.current?.getTracks().forEach((track) => track.stop()); setIsRecording(false); setIsBusy(true); setStatus("Transcribing…"); try { const blob = new Blob(chunks.current, { type: recorder.current?.mimeType || "audio/webm" }); const job = await api.uploadRecording(blob); setStatus("HealthScribe is processing the recording…"); await waitForCompletion(job.id); await openTranscript(job.id, "Done."); await loadLibrary(); } catch (error) { setStatus(error instanceof Error ? `Could not transcribe: ${error.message}` : "Could not transcribe the recording."); } finally { setIsBusy(false); } };
  const toggleRecording = async () => { if (recorder.current?.state === "recording") { recorder.current.stop(); return; } try { stream.current = await navigator.mediaDevices.getUserMedia({ audio: true }); chunks.current = []; const nextRecorder = new MediaRecorder(stream.current); recorder.current = nextRecorder; nextRecorder.addEventListener("dataavailable", (event) => chunks.current.push(event.data)); nextRecorder.addEventListener("stop", () => void sendRecording(), { once: true }); nextRecorder.start(); setIsRecording(true); setStatus("Recording… press Stop when finished."); } catch (error) { setStatus(error instanceof Error ? `Microphone unavailable: ${error.message}` : "Microphone unavailable."); } };
  const playSegment = (index: number) => { const player = audio.current; if (!player || !transcript?.recording_url) { setStatus("Audio is not available for this transcript."); return; } if (index === activeSegment) { if (player.paused) void player.play().catch(() => setStatus("Audio playback could not start.")); else player.pause(); return; } player.currentTime = transcript.segments[index].start; setActiveSegment(index); void player.play().catch(() => setStatus("Audio playback could not start.")); };
  const transcriptViewer = <TranscriptViewer transcript={transcript} activeSegment={activeSegment} isPlaying={isPlaying} onPlaySegment={playSegment} onAudioTimeUpdate={(event) => setActiveSegment(transcript?.segments.findIndex((segment) => event.currentTarget.currentTime >= segment.start && event.currentTarget.currentTime < segment.end) ?? -1)} onAudioPlay={() => setIsPlaying(true)} onAudioPause={() => setIsPlaying(false)} onAudioEnded={() => { setIsPlaying(false); setActiveSegment(-1); }} />;
  const activeSessionLabel = transcripts.find((savedTranscript) => savedTranscript.id === activeId)?.label || activeId || "Session";
  const activeSessionLayout = activeSessionType === "scheduled" ? <ScheduledSessionLayout isRecording={isRecording} isBusy={isBusy} onToggleRecording={() => void toggleRecording()} /> : <CompletedSessionLayout sessionId={activeSessionLabel}>{transcriptViewer}</CompletedSessionLayout>;
  return <main className="mx-auto w-[min(92vw,1080px)] py-8 text-center"><section className="mb-6 flex flex-col gap-4 rounded-2xl border border-stone-200 bg-stone-50 p-5 text-left sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-medium text-emerald-800">Client workspace</p><h1 className="mt-1 text-xl font-semibold tracking-tight text-stone-900">Session review</h1><p className="mt-1 text-sm text-stone-600">Client-specific preferences and permissions apply across this workspace, not to one note or transcript.</p></div><ClientCareSettings isOpen={isCareSettingsOpen} onOpen={() => setIsCareSettingsOpen(true)} onClose={() => setIsCareSettingsOpen(false)} /></section>{sessionView === "cards" ? <><SessionCardCarousel transcripts={transcripts} activeId={activeId} error={libraryError} onOpen={(id) => void openTranscript(id)} onSelectScheduled={() => { setActiveId(null); setTranscript(null); setActiveSessionType("scheduled"); }} onEditSchedule={() => setIsCareSettingsOpen(true)} /><div className="mt-6 text-left" ref={(node) => { audio.current = node?.querySelector("audio") ?? null; }}>{activeSessionLayout}</div></> : <div className="mt-6 grid items-start gap-6 text-left md:grid-cols-[minmax(380px,440px)_minmax(0,1fr)]"><TranscriptLibrary transcripts={transcripts} activeId={activeId} error={libraryError} onOpen={(id) => void openTranscript(id)} /><div className="min-w-0" ref={(node) => { audio.current = node?.querySelector("audio") ?? null; }}>{activeSessionLayout}</div></div>}</main>;
}
