import type { SyntheticEvent } from "react";
import { ClinicalNote } from "@/components/session-review/clinical-note";
import { SpeakerLabelEditor } from "@/components/session-review/speaker-label-editor";
import type { Transcript } from "@/lib/types";

type Props = { transcript: Transcript | null; activeSegment: number; isPlaying: boolean; onPlaySegment: (index: number) => void; onAudioTimeUpdate: (event: SyntheticEvent<HTMLAudioElement>) => void; onAudioPlay: () => void; onAudioPause: () => void; onAudioEnded: () => void; onSpeakerChange: (speaker: string, value: string) => void; onSaveSpeakers: () => void; isSavingSpeakers: boolean };
const formatTime = (seconds: number) => `${Math.floor(seconds / 60)}:${Math.floor(seconds % 60).toString().padStart(2, "0")}`;

export function TranscriptViewer({ transcript, activeSegment, isPlaying, onPlaySegment, onAudioTimeUpdate, onAudioPlay, onAudioPause, onAudioEnded, onSpeakerChange, onSaveSpeakers, isSavingSpeakers }: Props) {
  const speakerIds = [...new Set(transcript?.segments.map((segment) => segment.speaker).filter((speaker): speaker is string => Boolean(speaker)) ?? [])];
  return <section className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-stone-200" aria-label="Transcript viewer"><h2 className="text-lg font-semibold">Transcript</h2>{!transcript ? <p className="mt-3 text-sm text-stone-500">Choose a saved transcript or make a new recording.</p> : <><p className="mt-3 text-sm text-stone-500">{transcript.segments.length ? `${transcript.segments.length} timestamped segments.` : "(No speech detected.)"}</p><ClinicalNote sections={transcript.clinical_note} /><ol className="mt-5 grid list-none gap-2 p-0">{transcript.segments.map((segment, index) => { const active = activeSegment === index; return <li key={`${segment.start}-${index}`}><button type="button" className={`w-full cursor-grab rounded-lg border border-transparent p-2 text-left text-sm hover:border-stone-200 hover:bg-stone-100 focus-visible:outline-2 focus-visible:outline-emerald-700 active:cursor-grabbing ${active ? "border-emerald-300 bg-emerald-50" : ""}`} aria-label={`${active && isPlaying ? "Pause" : "Play"} segment at ${formatTime(segment.start)}`} onClick={() => onPlaySegment(index)}><span className="mr-2 inline-block w-5 text-emerald-800" aria-hidden="true">{active && isPlaying ? "❚❚" : "▶"}</span><time className="mr-2 text-stone-500">[{formatTime(segment.start)}]</time>{segment.speaker ? <span className="mr-2 rounded-full bg-stone-200 px-2 py-0.5 text-xs font-bold text-stone-700">{transcript.speakers[segment.speaker] || segment.speaker}</span> : null}{segment.text.trim()}</button></li>; })}</ol>{transcript.recording_url ? <><audio className="mt-5 w-full" controls src={transcript.recording_url} onTimeUpdate={onAudioTimeUpdate} onPlay={onAudioPlay} onPause={onAudioPause} onEnded={onAudioEnded} /><a className="mt-2 inline-block text-sm font-medium text-emerald-800 underline" href={transcript.recording_url} download>Download recording</a></> : null}<SpeakerLabelEditor speakerIds={speakerIds} labels={transcript.speakers} onChange={onSpeakerChange} onSave={onSaveSpeakers} isSaving={isSavingSpeakers} /></>}</section>;
}
