import { useState, type SyntheticEvent } from "react";
import { ClinicalNote } from "@/components/session-review/clinical-note";
import { SpeakerLabelEditor } from "@/components/session-review/speaker-label-editor";
import type { Transcript } from "@/lib/types";

type Props = { transcript: Transcript | null; activeSegment: number; isPlaying: boolean; onPlaySegment: (index: number) => void; onAudioTimeUpdate: (event: SyntheticEvent<HTMLAudioElement>) => void; onAudioPlay: () => void; onAudioPause: () => void; onAudioEnded: () => void; onSpeakerChange: (speaker: string, value: string) => void; onSaveSpeakers: () => void; isSavingSpeakers: boolean };
const formatTime = (seconds: number) => `${Math.floor(seconds / 60)}:${Math.floor(seconds % 60).toString().padStart(2, "0")}`;

export function TranscriptViewer({ transcript, activeSegment, isPlaying, onPlaySegment, onAudioTimeUpdate, onAudioPlay, onAudioPause, onAudioEnded, onSpeakerChange, onSaveSpeakers, isSavingSpeakers }: Props) {
  const [isTranscriptExpanded, setIsTranscriptExpanded] = useState(false);
  const speakerIds = [...new Set(transcript?.segments.map((segment) => segment.speaker).filter((speaker): speaker is string => Boolean(speaker)) ?? [])];
  const transcriptSummary = transcript ? (transcript.segments.length ? `${transcript.segments.length} timestamped segments` : "No speech detected") : null;
  return <section className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-stone-200" aria-label="Transcript viewer"><h2 className="text-lg font-semibold">Transcript{transcriptSummary ? ` (${transcriptSummary})` : ""}</h2>{!transcript ? <p className="mt-3 text-sm text-stone-500">Choose a saved transcript or make a new recording.</p> : <><ClinicalNote sections={transcript.clinical_note} /><section className="relative mt-5 overflow-hidden rounded-xl bg-stone-100 text-stone-900 transition hover:bg-stone-200"><button type="button" className="w-full p-4 pr-12 text-left font-semibold focus-visible:outline-2 focus-visible:outline-offset-[-2px] focus-visible:outline-stone-700" aria-expanded={isTranscriptExpanded} onClick={() => setIsTranscriptExpanded((value) => !value)}><span>Transcript</span><span className={`absolute right-4 text-lg text-stone-600 ${isTranscriptExpanded ? "top-3" : "bottom-2"}`} aria-hidden="true">{isTranscriptExpanded ? "⌃" : "⌄"}</span></button>{!isTranscriptExpanded ? <p className="px-4 pb-4 text-sm text-stone-600">{transcriptSummary || "No transcript details available."}</p> : <ol className="grid list-none gap-2 px-4 pb-4 pt-1">{transcript.segments.map((segment, index) => { const active = activeSegment === index; return <li key={`${segment.start}-${index}`}><button type="button" className={`group w-full rounded-lg border border-transparent p-2 text-left text-sm hover:border-stone-200 hover:bg-white focus-visible:outline-2 focus-visible:outline-emerald-700 ${active ? "border-emerald-300 bg-emerald-50" : ""}`} aria-label={`${active && isPlaying ? "Pause" : "Play"} segment at ${formatTime(segment.start)}`} onClick={() => onPlaySegment(index)}><span className={`mr-2 inline-block w-5 text-emerald-800 opacity-0 transition-opacity group-hover:opacity-100 group-focus-visible:opacity-100 ${active ? "opacity-100" : ""}`} aria-hidden="true">{active && isPlaying ? "❚❚" : "▶"}</span><time className="mr-2 text-stone-500">[{formatTime(segment.start)}]</time>{segment.speaker ? <span className="mr-2 rounded-full bg-stone-200 px-2 py-0.5 text-xs font-bold text-stone-700">{transcript.speakers[segment.speaker] || segment.speaker}</span> : null}{segment.text.trim()}</button></li>; })}</ol>}</section>{transcript.recording_url ? <><audio className="mt-5 w-full" controls src={transcript.recording_url} onTimeUpdate={onAudioTimeUpdate} onPlay={onAudioPlay} onPause={onAudioPause} onEnded={onAudioEnded} /><a className="mt-2 inline-block text-sm font-medium text-emerald-800 underline" href={transcript.recording_url} download>Download recording</a></> : null}<SpeakerLabelEditor speakerIds={speakerIds} labels={transcript.speakers} onChange={onSpeakerChange} onSave={onSaveSpeakers} isSaving={isSavingSpeakers} /></>}</section>;
}
